version: '2'

services:
  client1:
    extends:
      file: docker-common.yml
      service: client-base
    networks:
      - net1
  client2:
    extends:
      file: docker-common.yml
      service: client-base
    networks:
      - net2

networks:
  net1:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: net1
    ipam:
      config:
      - subnet: 1.1.1.0/24
  net2:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: net2
    ipam:
      config:
      - subnet: 2.2.2.0/24
